In [1]:
import pandas as pd

In [3]:
import os

# ✅ CSV 파일들이 있는 폴더 경로
folder_path =  "C:\\Users\\kelly\\Desktop\\GitHub\\predict_energy\\태양광\\1. 데이터 전처리 및 EDA\\추가 발전소\\당진자재창고(21.1-24.6)" # 예: 'data/' 또는 './csv_files/'

# ✅ 해당 폴더 내 모든 CSV 파일 이름 가져오기
file_list = [file for file in os.listdir(folder_path) if file.endswith('.csv')]

# ✅ 각 CSV 파일을 읽어서 리스트에 저장
df_list = [pd.read_csv(os.path.join(folder_path, file), encoding='cp949') for file in file_list]

# ✅ 데이터프레임들을 하나로 병합
merged_df = pd.concat(df_list, ignore_index=True)

# ✅ 병합된 결과를 새로운 CSV로 저장 (선택)
merged_df.to_csv('merged_result.csv', index=False, encoding='utf-8-sig')

In [4]:
df = pd.read_csv("merged_result.csv", encoding = "utf-8")

In [5]:
df.head()

,지점,지점명,일시,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),현지기압(hPa),일조(hr),일사(MJ/m2),적설(cm),전운량(10분위)
0,129,서산,2021-01-01 00:00,-6.0,0.0,0.4,0.0,91.0,1024.3,NaN,NaN,2.8,7.0
1,129,서산,2021-01-01 01:00,-5.7,NaN,0.2,0.0,91.0,1024.3,NaN,NaN,3.2,6.0
2,129,서산,2021-01-01 02:00,-6.0,NaN,0.0,0.0,92.0,1024.4,NaN,NaN,3.2,6.0
3,129,서산,2021-01-01 03:00,-6.5,0.0,1.0,90.0,91.0,1024.4,NaN,NaN,3.1,6.0
4,129,서산,2021-01-01 04:00,-8.3,NaN,0.3,0.0,90.0,1024.1,NaN,NaN,3.0,0.0

In [6]:
df = df.drop(columns=["지점"])

In [7]:
df.head()

,지점명,일시,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),현지기압(hPa),일조(hr),일사(MJ/m2),적설(cm),전운량(10분위)
0,서산,2021-01-01 00:00,-6.0,0.0,0.4,0.0,91.0,1024.3,NaN,NaN,2.8,7.0
1,서산,2021-01-01 01:00,-5.7,NaN,0.2,0.0,91.0,1024.3,NaN,NaN,3.2,6.0
2,서산,2021-01-01 02:00,-6.0,NaN,0.0,0.0,92.0,1024.4,NaN,NaN,3.2,6.0
3,서산,2021-01-01 03:00,-6.5,0.0,1.0,90.0,91.0,1024.4,NaN,NaN,3.1,6.0
4,서산,2021-01-01 04:00,-8.3,NaN,0.3,0.0,90.0,1024.1,NaN,NaN,3.0,0.0

In [8]:
df.to_csv("서산 병합.csv", encoding="utf-8")