In [1]:
import pandas as pd

In [45]:
df = pd.read_csv("C:\Users\kelly\OneDrive\바탕 화면\태양광\한국서부발전\한국서부발전(주)_태양광 발전 현황_20230630.csv", encoding = "cp949")

In [47]:
df.head(3)

,발전기명,년월일,설비용량(MW),01시,02시,03시,04시,05시,06시,07시,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,세종시폐기물매립장태양광,2017-01-01,1.628,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,742080.0,334440.0,87240.0,2880.0,4320.0,0.0,0.0,0.0,0.0,0.0
1,안산연성정수장태양광,2017-01-01,1.490,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,304800.0,230400.0,31200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,영암에프원태양광b,2017-01-01,13.296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7344000.0,5155200.0,2131200.0,134400.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
df.columns[3:]

Index(['01시', '02시', '03시', '04시', '05시', '06시', '07시', '08시', '09시', '10시',
       '11시', '12시', '13시', '14시', '15시', '16시', '17시', '18시', '19시', '20시',
       '21시', '22시', '23시', '24시'],
      dtype='object')

In [39]:
#시간별 발전량 열 추출(3번 열~끝까지)
hourly_columns = df.columns[3:]

#melt 함수로 long-format으로 변환
hour_generationQuantity = df.melt(id_vars = df.columns[ :3],
                                 value_vars = hourly_columns,
                                 var_name = "시간",
                                 value_name = "해당 시간 발전량(kWh)")

In [41]:
hour_generationQuantity

                발전기명         년월일  설비용량(MW)   시간  해당 시간 발전량(kWh)
0       세종시폐기물매립장태양광  2017-01-01     1.628  01시             0.0
1         안산연성정수장태양광  2017-01-01     1.490  01시             0.0
2          영암에프원태양광b  2017-01-01    13.296  01시             0.0
3       세종시폐기물매립장태양광  2017-01-02     1.628  01시             0.0
4         안산연성정수장태양광  2017-01-02     1.490  01시             0.0
...              ...         ...       ...  ...             ...
170611    안산연성정수장태양광  2023-06-29     1.490  24시             0.0
170612     영암에프원태양광b  2023-06-29    13.296  24시             0.0
170613  세종시폐기물매립장태양광  2023-06-30     1.628  24시             0.0
170614    안산연성정수장태양광  2023-06-30     1.490  24시             0.0
170615     영암에프원태양광b  2023-06-30    13.296  24시             0.0

[170616 rows x 5 columns]

In [43]:
hour_generationQuantity.to_csv("한국서부발전_시간별_발전량_utf-8.csv", index = False, encoding="utf-8-sig")