In [1]:
import pandas as pd

In [12]:
df = pd.read_csv("C:\\Users\\kelly\\Desktop\\GitHub\\predict_energy\\태양광\\1. 데이터 전처리 및 EDA\\추가 발전소\\감우리(충주, 제천, 청주)\\감우리 20210801-20220801 2차병합.csv", encoding = "utf-8")

In [14]:
df.head()

,Unnamed: 0,일시,지점,지점명,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),현지기압(hPa),일조(hr),일사(MJ/m2),적설(cm),전운량(10분위)
0,0,2021-08-01 00:00:00,127,충주,25.7,NaN,0.5,90,87,988.2,NaN,NaN,NaN,4.0
1,1,2021-08-01 01:00:00,127,충주,25.7,NaN,0.9,90,87,988.1,NaN,NaN,NaN,3.0
2,2,2021-08-01 02:00:00,127,충주,25.1,NaN,0.7,110,89,987.9,NaN,NaN,NaN,3.0
3,3,2021-08-01 03:00:00,127,충주,25.2,NaN,0.5,90,88,987.9,NaN,NaN,NaN,8.0
4,4,2021-08-01 04:00:00,127,충주,24.8,NaN,1.3,70,90,987.8,NaN,NaN,NaN,4.0

In [16]:
#c첫번째 열 제거
df = df.drop(df.columns[0], axis=1)

In [20]:
df.head()

,일시,지점,지점명,기온(°C),강수량(mm),풍속(m/s),풍향(16방위),습도(%),현지기압(hPa),일조(hr),일사(MJ/m2),적설(cm),전운량(10분위)
0,2021-08-01 00:00:00,127,충주,25.7,NaN,0.5,90,87,988.2,NaN,NaN,NaN,4.0
1,2021-08-01 01:00:00,127,충주,25.7,NaN,0.9,90,87,988.1,NaN,NaN,NaN,3.0
2,2021-08-01 02:00:00,127,충주,25.1,NaN,0.7,110,89,987.9,NaN,NaN,NaN,3.0
3,2021-08-01 03:00:00,127,충주,25.2,NaN,0.5,90,88,987.9,NaN,NaN,NaN,8.0
4,2021-08-01 04:00:00,127,충주,24.8,NaN,1.3,70,90,987.8,NaN,NaN,NaN,4.0

In [22]:
df.to_csv("감우리 20210801-20220801 최종.csv", index=False, encoding="utf-8")